/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbconnect;

import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabrielrodriguez
 */
public class adminpanel2 extends javax.swing.JFrame {

    /**
     * Creates new form adminpanel2
     */
    public adminpanel2() {
        initComponents();
        show_user();
    }
        public ArrayList<User> userlist(){
        ArrayList<User> userList = new ArrayList<>();
        try{
        Configurador c = Configurador.getInstance();
        System.out.println(c.getUsername());
        dbconnect s = dbconnect.getInstance();
        ResultSet loginu = s.st.executeQuery("select Username,Nombre_u,estado_u from usuarios order by estado_u");
        User user;
        while (loginu.next()){
            user =new User(loginu.getString("Username"),loginu.getString("Nombre_u"),loginu.getString("estado_u"));
            userList.add(user);
        }
                
        } catch (Exception e) {
	System.out.println("Revise el contacto cargado en la lista"+ e); //TODO: handle exception
        	}
        return userList;
    }
    public void show_user(){
        ArrayList<User> list = userlist();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_user.getModel();
        Object [] row = new Object [3];
        for(int i=0;i<list.size ();i++){
            row[0]=list.get(i).getnombre();
            row[1]=list.get(i).getapellido();
            row[2]=list.get(i).getestado();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textuser = new javax.swing.JTextField();
        textpasswd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_user = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jButton1.setText("OBTENER CONTRASEÑA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("REESTABLECER ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable_Display_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Nombre", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable_Display_user);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textuser, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textpasswd)))
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
            String usuario = textuser.getText();
            String newpasswd = textpasswd.getText();


            Resetpasswd(usuario,newpasswd);


    } catch (Exception e1) {
    System.out.println("Revise lo ingresado"+ e1); //TODO: handle exception
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
            String usuario = textuser.getText();
            String passwd = textpasswd.getText();


            Getpasswd(usuario,passwd);


    } catch (Exception e1) {
    System.out.println("Revise lo ingresado"+ e1); //TODO: handle exception
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpanel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpanel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpanel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpanel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpanel2().setVisible(true);
            }
        });
    }

	public static void Getpasswd(String usuario, String passwd) {	
		
		String passwdc = "";
		boolean ingreso = true;
		
		if (ingreso == true) {   
		try {
			
	        //get connection to Database
                dbconnect s = dbconnect.getInstance();
                ResultSet loginu = s.st.executeQuery("select Contrasena_u from usuarios where Username = '"+ usuario +"';");
	        //Connection mycon = DriverManager.getConnection("jdbc:mysql://localhost:3306/agenda", "root", "password");
	        //Statement mylog = mycon.createStatement();
	        //ResultSet loginu = mylog.executeQuery
	        
	        while (loginu.next()){
	        	passwdc = (loginu.getString("Contrasena_u"));
	        	
	        }
	        
	        if(ingreso == true) {
	        	//mylog.executeUpdate(
	        	JOptionPane.showMessageDialog(null, "CONTRASEÑA: "+ passwdc.toUpperCase());
	        }
	        else
	        { 
	        	JOptionPane.showMessageDialog(null, "USUARIO " + usuario.toUpperCase() + " "+ "NO ENCONTRADO EN LA BASE"); 
	        }
	        
		} catch (Exception e) {
			System.out.println("Revise lo ingresado"+ e); //TODO: handle exception
			JOptionPane.showMessageDialog(null, "LOS TRES VALORES DEBEN SER CARGADOS");
			     }	 
			}	
		}
	public static void Resetpasswd(String usuario, String newpasswd) {	
	    String newpasswdc = newpasswd;
		String passwbd = "";
		boolean ingreso = true;
		
		if (ingreso == true) {   
		try {
			
	        //get connection to Database
	        //Connection mycon = DriverManager.getConnection("jdbc:mysql://localhost:3306/agenda", "root", "password");
	        //Statement mylog = mycon.createStatement();
	        //ResultSet loginu = mylog.executeQuery
	        dbconnect s = dbconnect.getInstance();
                ResultSet loginu2 = s.st.executeQuery("select Contrasena_u from usuarios where Username = '"+ usuario +"';");
                
                
	        while (loginu2.next()){
	        	passwbd = (loginu2.getString("Contrasena_u"));
	        }
	        
	        if(newpasswdc != "") {
	        s.st.executeUpdate("UPDATE usuarios SET Contrasena_u = '"+ newpasswd +"' WHERE Username = '"+ usuario + "';"); 
	        	JOptionPane.showMessageDialog(null, "NUEVA CONTRASEÑA: "+ newpasswd.toUpperCase());
	        }
	        else
	        { 
	        	JOptionPane.showMessageDialog(null, "USUARIO " + usuario.toUpperCase() + " "+ "NO ENCONTRADO EN LA BASE"); 
	        }
	        
		} catch (Exception e) {
			System.out.println("Revise lo ingresado"+ e); //TODO: handle exception
			JOptionPane.showMessageDialog(null, "LOS TRES VALORES DEBEN SER CARGADOS");
			     }	 
			}	
		}    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_user;
    private javax.swing.JTextField textpasswd;
    private javax.swing.JTextField textuser;
    // End of variables declaration//GEN-END:variables
}
