/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbconnect;

//mport static dbconnect.login_system.Identificacion;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author gabrielrodriguez
 */
public class login2 extends javax.swing.JFrame {
    
  
       
    /**
     * Creates new form login2
     */
    private login2() {
       
       initComponents();
       
        
      
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtcontrasena = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        jLabel1.setText("USUARIO");

        jLabel2.setText("PASSWORD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnlogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcontrasena)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnlogin))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        	try {
	    Configurador c = Configurador.getInstance();

            String username = txtusuario.getText();
            String passwd = txtcontrasena.getText();

            c.setUsername(username);
            c.setPassword(passwd);
            Identificacion(username, passwd);
			        
        } catch (Exception e1) {
        System.out.println("Revise lo ingresado"+ e1); //TODO: handle exception
                }
    }//GEN-LAST:event_btnloginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
			    add_user2 info = new add_user2();
			    add_user2.main(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtcontrasena;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
public static void Identificacion(String username, String passwd) {	        
                
	        String userv = null;
	        String contrasenav = null;
                String  estadov = null;
		boolean ingreso = true;
		
				
		 
                
                try{
                dbconnect s = dbconnect.getInstance();
                ResultSet loginu = s.st.executeQuery("select Username,Contrasena_u,estado_u from usuarios where Username = '"+ username + "'AND Contrasena_u = '" + passwd + "';");

	        while (loginu.next()){
	        	estadov = (loginu.getString("estado_u"));
                }
                if (estadov.equals("Inhabilitado")){
                    JOptionPane.showMessageDialog(null, "EL USUARIO: " + username.toUpperCase() + " NO SE ENCUENTRA HABILITADO");  
                    ingreso = false;
                }    
                
                } catch (Exception e) {
                System.out.println("Revise lo ingresado"+ e); //TODO: handle exception
                JOptionPane.showMessageDialog(null, "USER O PASS ERROR");
                }    
                    
                if (ingreso == true) {     
		try {
	        dbconnect s = dbconnect.getInstance();
                ResultSet loginu = s.st.executeQuery("select Username,Contrasena_u,estado_u from usuarios where Username = '"+ username + "'AND Contrasena_u = '" + passwd + "';");

                
	        while (loginu.next()){
	        	userv = (loginu.getString("Username"));
	        	//System.out.println(userv);
	        }
	        while (loginu.next()){
	        	contrasenav = (loginu.getString("Contrasena_u"));
	        	//System.out.println(contrasenav);
	        } 
                	while (loginu.next()){
	        	estadov = (loginu.getString("estado_u"));
	        //	System.out.println(estadov);
	        } 
                
                //if (estadov.equals("Inhabilitado")) {
                //   JOptionPane.showMessageDialog(null, "EL USUARIO: " + username.toUpperCase() + "NO SE ENCUENTRA HABILITADO"); 
                //}
                if (userv.equals("root")) {
			    adminpanel2 info = new adminpanel2();
			    adminpanel2.main(null);
	        }
	        else if(userv.equals(username) || contrasenav.equals(passwd)) {
	        	JOptionPane.showMessageDialog(null, "BIENVENIDO " + username.toUpperCase()); 
			    agendados info = new agendados();
			    agendados.main(null);
	        }
	        else
	        { 
	        	JOptionPane.showMessageDialog(null, "USER O PASS ERROR");
	        }
		} catch (Exception e) {
			System.out.println("Revise lo ingresado"+ e); //TODO: handle exception
			JOptionPane.showMessageDialog(null, "USER O PASS ERROR");
			}	 
		}
	  }
	
}
